language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    - stage: build
      jdk: openjdk8
      script: mvn clean test
      branches:
        except:
          - master
    - stage: sonar
      jdk: openjdk8
      script: mvn sonar:sonar -Dsonar.projectKey=shakespeare-lang-compiler -Dsonar.host.url=$SONAR_ENDPOINT -Dsonar.login=$SONAR_LOGIN
      branches:
        except:
          - master